### ISSUE TITLE
Problems compiling CommandCenter BOT on Linux (ubuntu 17.04, debian 9 and Fedora26).

### ISSUE THREAD

**Issue by jhor296** [davechurchill/commandcenter#33] opened 2017-09-21 23:06 UTC
After running "cmake .", in the compilation process:

.... commandcenter/src/BuildingPlacer.cpp: In member function 'sc2::Point2D BuildingPlacer::getRefineryPosition()': ........./commandcenter/src/BuildingPlacer.cpp:244:33: error: invalid initialization of reference of type 'const sc2::Unit&' from expression of type 'const sc2::Unit* '
           if (!Util::IsGeyser(unit))

There are also other problems in BuildingPlacer.cpp with request for member 'pos' in 'unit' pointer.

-----------------

src/CMakeFiles/CommandCenter.dir/build.make:278 with failure of the instructions for the target

------------------

Thank you very much for your work and sorry for my bad english.

**Comment by davechurchill** [comment] 2017-09-21 23:14
This is caused by a change in the new version of the API, I am in the process of fixing it

**Comment by davechurchill** [comment] 2017-09-28 05:35
Fixed now

**Closed by davechurchill** 2017-09-28 05:35 UTC
